### PR TITLE
Return studies image count and titles

### PR DESCRIPTION
**Pull request by khaledk2**
This PR addresses issue #34 and issue #35. 

The `/submitquery_returnstudies/` endpoint will return all the containers, each will  have an IDR name, the image count, a title and the recourse type (project, screen). It should be something like this:

```
 {
        "Name (IDR number)": "idr0041-cai-mitoticatlas/experimentA",
        "image count": 60480,
        "title": "Experimental and computational framework for a dynamic protein atlas of human cell division",
        "type": "project"
}
```
It has been deployed on the idr-testing.

@will-moore Could you please check this and let me know what you think?

### CODE REVIEW

**Comment by will-moore** [comment]
Thanks, that's great. Used in https://github.com/IDR/idr-gallery/pull/8 and deployed on idr-testing.
I realise I needed one other thing, in order to generate a link to each study, and that is the Project or Screen ID. Could you add that too? Thanks

**Comment by sbesson** [comment]
Adding one general comment here which has less to do with the logic of the new endpoint and more about the the name of the new endpoint:

`idr0041-cai-mitoticatlas/experimentA` is not a study as defined by the IDR vocabulary. It is the name of the first experiment of the study with accession number `idr0041` which is composed of 3 experiments.

I think the name reflects existing design choices of the UI. For instance the result table of http://idr.openmicroscopy.org/search/?query=mapr_cellline:hela will returns experiments and screens as different rows but each of row is assigned a different study ID which is derived from the accession and the experiment/screen suffix.

As per the historical nature of this UI, I do not think this is something we want to address/scope within the first phase of the new search UI work.
Importantly though, the reusage of the term creates a layer of internal confusion. For instance, http://idr.openmicroscopy.org/search/?query=mapr_compound:Nomegestrol%20acetate returns 8 studies but really images are distributed within 5 studies.

In the scope of this PR, the first question is whether this API should be called `submitquery_returnstudies` or whether we rename it to reflect the objects being returned.

In a future phase, a wider question is whether we want to introduce some API allowing to group several screens/experiments by study and possibly reflect this hierarchy in the UI

**Comment by will-moore** [comment]
I've struggled with this naming issue for a long time. There is no collective name for "experiments and screens" in any IDR or OMERO UI or model. And there is no Object in OMERO that is equivalent of a Study!
However, I think the name could be improved...
E.g. `/submitquery/studies/` (or whatever name we choose) instead of `/submitquery_returnstudies`.
This is similar to returning the Images for a Dataset: https://idr.openmicroscopy.org/api/v0/m/datasets/100/images/

**Comment by khaledk2** [comment]
I have added the `container's id `to the returned results and deployed it on `idr-testing`.

I think we may change the endpoint to avoid using  `study`; we may use `container` instead. The endpoint may be something like  `/submitquery_returncontainers` or `/submitquery/containers/ `.

**Comment by sbesson** [comment]
> I've struggled with this naming issue for a long time. There is no collective name for "experiments and screens" in any IDR or OMERO UI or model. 

Agreed. In the OME model, Project and Screen are two well-defined top-level elements with no relationship to each other apart from the fact they ultimately contain images.
Internally, our tooling has the concept of `study components`  which is effectively the namespace used for some of the map annotations - https://github.com/IDR/idr-utils/blob/f4c13b0f18f6dbb0d787988d9793f4ba683806e0/pyidr/study_parser.py#L98.  But this is not something that we formalized officially.

> And there is no Object in OMERO that is equivalent of a Study!

Also agreed. A study will be a collection of a combination of screens and experiments with associated metadata and there is no such concept in the OME model or OMERO.

If the definition of this intermediate concept is too much at the given time, a possibility would be to keep studies as the primary concept return by this endpoint but use the return structure to communicate the layout:

```
 {
        "Study accession": "idr0041",
        "experiments" : [
             {
                "Name": "idr0052-walther-condensinmap/experimentA",
                "image count": xxx,
                 "title": ...,
                 "type": "project"
             },
             {                
                 "Name": "idr0052-walther-condensinmap/experimentB",
                "image count": yyy,
                 "title": "...,
                 "type": "project"
             }
        ],
},
{
...
}
```

Advantage of the proposal above is that the UI could simply iterate over the experiments/screens for now but in future iteration, it could reflect the fact that several experiments are part of the same study.

**Comment by will-moore** [comment]
But I think we need to remember that this repo is `omero_search_engine` not `idr_search_engine`.
It is being consumed by `idr-gallery` so it's really the responsibility of the UI to add the IDR concepts, not the OMERO-based api.

**Comment by sbesson** [comment]
> But I think we need to remember that this repo is omero_search_engine not idr_search_engine.
It is being consumed by idr-gallery so it's really the responsibility of the UI to add the IDR concepts, not the OMERO-based api.

Makes sense to me and I think the proposal in https://github.com/ome/omero_search_engine/pull/41#issuecomment-1230505646 addresses this separation.
The other alternative would be to have separate APIs for returning projects and screens.

**Comment by khaledk2** [comment]
If will return all the key/value pairs list, along with the description, name, type and id, it will be something like this JSON,
What do you think? 

```
{
   "description":"Publication Title\nOptical pooled screens in human cells\n\nExperiment Description\nOptical pooled CRISPR knockout screen in HeLa cells for regulators of p65 translocation upon stimulation by IL-1b or TNF-a, detected by imaging a p65-mNeonGreen fluorescent reporter. CRISPR sgRNAs are detected by sequencing proxy barcodes in cells transduced with the lentiGuide-BC vector. Included cycles of sequencing-by-synthesis (SBS): 1, 2, 3, 4, 5, 6, 7, 8, 9.",
   "id":1503,
   "key_values":[
      {
         "index":0,
         "name":"Experiment A",
         "value":"https://idr.openmicroscopy.org/webclient/?show=project-1503"
      },
      {
         "index":0,
         "name":"Sample Type",
         "value":"cell"
      },
      {
         "index":1,
         "name":"Experiment B",
         "value":"https://idr.openmicroscopy.org/webclient/?show=project-1505"
      },
      {
         "index":1,
         "name":"Organism",
         "value":"Homo sapiens"
      },
      {
         "index":2,
         "name":"Experiment C",
         "value":"https://idr.openmicroscopy.org/webclient/?show=project-1504"
      },
      {
         "index":2,
         "name":"Study Type",
         "value":"in situ sequencing"
      },
      {
         "index":3,
         "name":"Experiment D",
         "value":"https://idr.openmicroscopy.org/webclient/?show=project-1506"
      },
      {
         "index":3,
         "name":"Imaging Method",
         "value":"fluorescence microscopy"
      },
      {
         "index":4,
         "name":"Experiment E",
         "value":"https://idr.openmicroscopy.org/webclient/?show=project-1502"
      },
      {
         "index":4,
         "name":"Publication Title",
         "value":"Optical pooled screens in human cells"
      },
      {
         "index":5,
         "name":"Experiment F",
         "value":"https://idr.openmicroscopy.org/webclient/?show=project-1507"
      },
      {
         "index":5,
         "name":"Publication Authors",
         "value":"Feldman D, Singh A, Schmid-Burgk JL, Carlson RJ, Mezger A, Garrity AJ, Zhang F, Blainey P"
      },
      {
         "index":6,
         "name":"Overview",
         "value":"https://idr.openmicroscopy.org/webclient/?show=project-1551"
      },
      {
         "index":6,
         "name":"PubMed ID",
         "value":"31626775 https://www.ncbi.nlm.nih.gov/pubmed/31626775"
      },
      {
         "index":7,
         "name":"PMC ID",
         "value":"PMC6886477 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6886477"
      },
      {
         "index":8,
         "name":"Publication DOI",
         "value":"10.1016/j.cell.2019.09.016 https://doi.org/10.1016/j.cell.2019.09.016"
      },
      {
         "index":9,
         "name":"Release Date",
         "value":"2021-01-27"
      },
      {
         "index":10,
         "name":"License",
         "value":"CC BY 4.0 https://creativecommons.org/licenses/by/4.0/"
      },
      {
         "index":11,
         "name":"Copyright",
         "value":"Feldman et al"
      },
      {
         "index":12,
         "name":"Data Publisher",
         "value":"University of Dundee"
      },
      {
         "index":13,
         "name":"Annotation File",
         "value":"idr0071-experimentA-annotation.csv https://github.com/IDR/idr0071-feldman-crisprko/blob/HEAD/experimentA/idr0071-experimentA-annotation.csv"
      }
   ],
   "name":"idr0071-feldman-crisprko/experimentA",
   "type":"project"
}
```

**Comment by jburel** [comment]
If I remember correctly, 
we avoided using ``"https://idr.openmicroscopy.org/webclient/?show=project-1503"`` as a link and opted for something like ``"link": "https://idr.openmicroscopy.org/search/?query=Name:idr0002",``.  So returning a url might not be the best strategy
cc @sbesson

**Review by will-moore — APPROVED** [review]
This is working for me now, thanks.

**Comment by will-moore** [comment]
@khaledk2 I like `/submitquery/containers/`
https://github.com/ome/omero_search_engine/pull/41#issuecomment-1231798105 looks good, but I think it should be `"key"` instead of `"name"` for the keys.
Let me know when that's going to happen, as it will break my current code.

**Comment by khaledk2** [comment]
I think using key instead of name is related to [https://github.com/ome/omero_search_engine/issues/42](https://github.com/ome/omero_search_engine/issues/42). If everyone is happy with this change I can change the name to key and start working with the implementation for issue  #42.

**Comment by will-moore** [comment]
👍 Looks good - let me know when you're planning to deploy this to idr-testing, so I can update the UI at the same time

**Comment by khaledk2** [comment]
I have changed the `name` to `key`.  Also,  the endpoint  has been changed to `/submitquery/containers/` instead of  `/submitquery_returnstudies/`

It is ready for deployment, I will deploy it tomorrow morning after the standup meeting.

**Pull request merged**
