### PR TITLE
Doc review

### PR DESCRIPTION
**Pull request by jburel**
* Review the instructions and fix formatting issue
* Fix warning in the sphinx doc

### CODE REVIEW

**Comment by khaledk2** [comment]
Thank you for taking the time to check and fix the documentation.

It looks good but it has some file link errors, for example in 
[docs/configuration/configuration_installation.rst](https://github.com/jburel/omero_search_engine/edit/cleanup/docs/configuration/configuration_installation.rst)

`app_config.yml <configurations/app_config.yml>`
should be:
 `app_config.yml </configurations/app_config.yml>`_ 

Should I fix them?

**Comment by jburel** [comment]
@khaledk2 documentation on RTD https://jburel-omero-search-engine.readthedocs.io/en/latest/

**Comment by khaledk2** [comment]
I have built it locally and worked fine, I have checked the link you have posted and it looks good.
Sorry, It seems that I have checked it online at the project repo and using Pycharm IDE rather than building the documents.

**Comment by jburel** [comment]
Merging so we can move forward

**Pull request merged**
