### PR TITLE
Search projects& screens using name and description 

### PR DESCRIPTION
**Pull request by khaledk2**
It is possible to get all the screen and projects names using the following endpoint

http://idr-testing.openmicroscopy.org/searchengine//api/v1/resources/all/names/

It is possible to replace `all `with a `project `to get the project names only or by `screen `to get the screen names only.

This PR adds a search function to the screen and project name, i.e. it is possible to search for the `project ` and `screen `using a part of the name.  The user sets a `value `to the query, then it will search the names and returns the matching ones

http://idr-testing.openmicroscopy.org/searchengine//api/v1/resources/all/names/?value=idr0012

This addresses issue #54.

It has been deployed to the `idr-testing`.

@will-moore could you please check that and let me what do you think?

### CODE REVIEW

**Comment by will-moore** [comment]
Thanks - I guess this won't be deployed for testing until the first 'release' is done / tagged, so I'll need to return to this later...

**Comment by will-moore** [comment]
Ah, yes - that's working. Thanks.
Also tried e.g. https://idr-testing.openmicroscopy.org/searchengine/api/v1/resources/screen/names/?value=cell
LGTM 👍

**Comment by will-moore** [comment]
Ah, the comments I added to https://github.com/ome/omero_search_engine/issues/54#issuecomment-1323813690 should probably have been here (on the PR) instead...

Thanks for those fixes @khaledk2 - let me know when they're deployed. Cheers.

**Comment by khaledk2** [comment]
The search is case insensitive and returns a list of dicts, each containing container (screen or project) id, name and description.

It has been deployed in `id-testing`, please check it and let me know what you think.

**Comment by will-moore** [comment]
looks good, thanks...

**Comment by khaledk2** [comment]
In addition to searching by the container `name `using `submitquery `endpoint, searching by container (project/screen) `description `has been added, the query should be something like that:

```
{
"query_details": {
"and_filters": [
{
"name": "description",
"value": "Imaging a whole mouse central nervous system with the mesoSPI",
"operator": "contains",
"resource": "container"
}
],
"or_filters": [
],
"case_sensitive": false
}
}
```

It has been deployed in `idr-testing, `@will-moore could you please check that and let me what do you think?

**Comment by will-moore** [comment]
@khaledk2 Thanks - that seems to be working for me.

However, I think I will hold-off adding support for Description just now because there are issues when you pick a matching Description from auto-complete:

Screenshot 2022-12-14 at 14 02 00

It tries to search using the full Description. However, the line-breaks are not preserved, so we do a search for description "contains" or "equals":
`
Publication TitleAutomated quantification of synaptic boutons reveals their 3D distribution in the honey bee mushroom bodyExperiment DescriptionTo study the spatial distribution of synaptic complexes called microglomeruli in the mushroom body neuropils of the honeybee brain, those structures where imaged by two-photon microscopy. A data analysis method was developed to automatically obtain the loci of those structures from large volume samples allowing to analyse their 3D density distribution.
`
and this returns no results.
The actual description in this case is `To study the spatial distribution of synaptic complexes called microglomeruli in the mushroom body neuropils of the honeybee brain, those structures where imaged by two-photon microscopy. A data analysis method was developed to automatically obtain the loci of those structures from large volume samples allowing to analyse their 3D density distribution.`

I would prefer not to have to add logic to parse that. Ideally we should first clean up the descriptions in IDR.

**Comment by khaledk2** [comment]
Yes, I see what you mean, this is the container description from the database:

`Publication Title\nAutomated quantification of synaptic boutons reveals their 3D distribution in the honey bee mushroom body\n\nExperiment Description\nTo study the spatial distribution of synaptic complexes called microglomeruli in the mushroom body neuropils of the honeybee brain, those structures where imaged by two-photon microscopy. A data analysis method was developed to automatically obtain the loci of those structures from large volume samples allowing to analyse their 
3D density distribution.`

Searchengine saves it without any modifications and I think the UI removes the '\n'. 

So the query should be like that to return results:

```
{
"query_details": {
"and_filters": [
{
"name": "description",
"value": "Publication Title\nAutomated quantification of synaptic boutons reveals their 3D distribution in the honey bee mushroom body\n\nExperiment Description\nTo study the spatial distribution of synaptic complexes called microglomeruli in the mushroom body neuropils of the honeybee brain, those structures where imaged by two-photon microscopy. A data analysis method was developed to automatically obtain the loci of those structures from large volume samples allowing to analyse their 3D density distribution.",
"operator": "equals",
"resource": "container"
}
],
"or_filters": [
],
"case_sensitive": false
}
}
```
or get the actual container  `description` and send a query like that:

```
{
"query_details": {
"and_filters": [
{
"name": "description",
"value": "To study the spatial distribution of synaptic complexes called microglomeruli in the mushroom body neuropils of the honeybee brain, those structures where imaged by two-photon microscopy. A data analysis method was developed to automatically obtain the loci of those structures from large volume samples allowing to analyse their 3D density distribution.",
"operator": "contains",
"resource": "container"
}
],
"or_filters": [
],
"case_sensitive": false
}
}

```
Yes, I think it would be a good idea to fix that at the IDR database level and make the `description` contain `description `only.

**Comment by sbesson** [comment]
> I would prefer not to have to add logic to parse that. Ideally we should first clean up the descriptions in IDR.
>  Yes, I think it would be a good idea to fix that at the IDR database level and make the description contain description only.

I am totally supportive of any clean up/re-annotation effort that aims at improving the searchability of this metadata but we probably need to work on a more concrete proposal.

For reference, the content of these descriptions was defined in the early days and was originally populated by hand. These decisions have been turned into some utilities to automate the annotation of these containers in a more systematic ways and the relevant code is in https://github.com/IDR/idr-utils/blob/1ba5e3810751b6df04ae0d0472a7a09c852d7e7a/pyidr/study_parser.py#L406-L426.

Historically, I think the construction of these descriptions reflect some of the mismatch between the IDR model and the OMERO model at a time where the webclient was the IDR entry point and there was neither a gallery app nor a search engine:

- each IDR study has a `Study Title`, a `Study Description` and usually a `Publication Title`. Both `Study Title` and `Publication Title` are currently stored in the key/value pairs for each container associated with the study
- an IDR study may be associated with an OMERO Project or Screen if it contains more than one screen or experiment
- each IDR experiment or screen has an `Experiment/Screen Description` and is associated to an OMERO Project or Screen

@will-moore @khaledk2 based on the above, is it possible to work out a proposal of how the metadata should be transformed ?

**Comment by will-moore** [comment]
@sbesson I'm not sure if you're proposing that we change the project/screen Description fields in IDR (to remove the `Study Title` and `Study Version History` to leave *only* the Description? (code to do this shouldn't be too hard).
Or if you're suggesting the logic to parse the proejct/screen.description -> `Description` should happen in the search engine indexing?
I would certainly prefer the first option.

Seems like a good start would be to update `def generate_description()`:

```
def generate_description(self, component):
        """Generate the description of the study/experiment/screen"""
        if "Type" in component:
            key = "%s Description" % component["Type"]
        else:
            key = "Study Description"
        return component[key]
```

**Comment by sbesson** [comment]
I am not suggesting anything in particular and from my side, all options should be on the table but I wanted to raise that any change will have to be run through the wider IDR team and the search engine cannot be the only element for consideration here. Summarizing pros and cons:

1. keep the current description and update the search engine to parse description
    Pros: does not break current user expectation or lose metadata
    Cons: injects a lot of IDR specifics into the search engine functionality
2. update the descriptions e.g. as in https://github.com/ome/omero_search_engine/pull/57#issuecomment-1352827460 and consume the description directly
    Pros: allows the searching functionality to treat the description field generically
    Cons: unclear whether metadata is lost or the user experience is degraded by updating these descriptions

Personally, I could definitely support a proposal moving towards option 2. Having descriptions structured according to an internal schema always feels someway misplaced while the rest of the metadata is using key/value pairs. But it might also reflect on the fact this allows to expose essential metadata e.g. `Publication Title` that would be otherwise somewhat hidden when clicking on a project/screen.

**Comment by khaledk2** [comment]
I have disabled the search by the container description and deployed it in `idr-testing`.

**Comment by jburel** [comment]
Discussed during the last search meeting, not exposed the ``description`` via search engine. Content in the description e.g. ``Publication Title`` should be removed.

**Comment by khaledk2** [comment]
The `description` is included in the results although the user can not search them, I will remove them.

**Comment by khaledk2** [comment]
I have removed the `container description` from the returned results and deployed it in `idr-testing`.

**Pull request merged**
